// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBenU9vf2mlEwwy73EBhUCMIo4n0C6mOXY',
    appId: '1:320727540393:web:1b36508b1c658324b67fb8',
    messagingSenderId: '320727540393',
    projectId: 'gomie-c8c21',
    authDomain: 'gomie-c8c21.firebaseapp.com',
    storageBucket: 'gomie-c8c21.firebasestorage.app',
    measurementId: 'G-DHZTTM50RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosQK2tQ07muYmkkQ6Suuh68qGt1C7dx0',
    appId: '1:320727540393:android:a3b73e7626f539f4b67fb8',
    messagingSenderId: '320727540393',
    projectId: 'gomie-c8c21',
    storageBucket: 'gomie-c8c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjsIX1MnnYKenOQDnGzs7hF9keGoNrCk',
    appId: '1:320727540393:ios:962c281cd43623e3b67fb8',
    messagingSenderId: '320727540393',
    projectId: 'gomie-c8c21',
    storageBucket: 'gomie-c8c21.firebasestorage.app',
    iosBundleId: 'com.example.gomie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjsIX1MnnYKenOQDnGzs7hF9keGoNrCk',
    appId: '1:320727540393:ios:962c281cd43623e3b67fb8',
    messagingSenderId: '320727540393',
    projectId: 'gomie-c8c21',
    storageBucket: 'gomie-c8c21.firebasestorage.app',
    iosBundleId: 'com.example.gomie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBenU9vf2mlEwwy73EBhUCMIo4n0C6mOXY',
    appId: '1:320727540393:web:f1a545a11e25df9ab67fb8',
    messagingSenderId: '320727540393',
    projectId: 'gomie-c8c21',
    authDomain: 'gomie-c8c21.firebaseapp.com',
    storageBucket: 'gomie-c8c21.firebasestorage.app',
    measurementId: 'G-JM4Z4MM55H',
  );
}
